# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160624_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='commission_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='external_payment_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='external_user_wallet_id',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('new', 'Выставлен'), ('paid', 'Оплачен'), ('fail', 'Отменен'), ('closed', 'Закрыт')], default='new', max_length=32),
        ),
    ]
