# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20160704_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Tariff'),
        ),
    ]
