# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screencast',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Article')),
                ('video', models.TextField(default='', verbose_name='Видео')),
            ],
            options={
                'db_table': 'screencasts',
            },
            bases=('articles.article',),
        ),
        migrations.CreateModel(
            name='ScreencastSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг')),
                ('position', models.IntegerField(default=0, verbose_name='Позиция')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('publ', 'Опубликовано'), ('hided', 'Скрыто')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
            ],
            options={
                'db_table': 'screencast_sections',
            },
        ),
        migrations.AddField(
            model_name='screencast',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screencasts', to='screencasts.ScreencastSection', verbose_name='Раздел'),
        ),
    ]
