# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Article')),
                ('stub', models.CharField(blank=True, max_length=10, null=True, verbose_name='Заглушка')),
            ],
            options={
                'db_table': 'blogs',
            },
            bases=('articles.article',),
        ),
    ]
