# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='src.articles.Article')),
                ('stub', models.CharField(blank=True, max_length=10, null=True, verbose_name='Заглушка')),
            ],
            options={
                'db_table': 'blogs',
            },
            bases=('articles.article',),
        ),
    ]
