# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='Заголовок')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Конспект')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Содержание статьи')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='Слаг')),
                ('type', models.CharField(choices=[('blog', 'Блог'), ('screencast', 'Скринкаст')], default='screencast', max_length=16, verbose_name='Тип')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('publ', 'Опубликовано'), ('hided', 'Скрыто')], default='draft', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Изменено')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
