# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('view_subscription_article', 'Может видеть статьи по подписке'),)},
        ),
        migrations.AddField(
            model_name='article',
            name='by_subscription',
            field=models.BooleanField(default=False, verbose_name='Доступ по подписке'),
        ),
    ]
