# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': (('view_subscription_article', 'Может видеть статьи по подписке'),)},
        ),
        migrations.AddField(
            model_name='article',
            name='by_subscription',
            field=models.BooleanField(default=False, verbose_name='Доступ по подписке'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
