# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=64)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('accepted', 'Оплативший'), ('rejected', 'Отказник')], default='new', max_length=16)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lending_registrations',
            },
        ),
    ]
