# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingregistration',
            name='details',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
