# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='Платный подписчик'),
        ),
    ]
