# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20160512_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_subscriber',
        ),
        migrations.AddField(
            model_name='myuser',
            name='access_till',
            field=models.DateField(null=True, verbose_name='Срок доступа'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='name'),
        ),
    ]
